### ISSUE TITLE
New category for maintenance: "stewardship"

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus-github-lottery#36]
@geoand and I have a bit of a specific role in that we somehow have a look at most of the areas and having a look at old issues from the external perspective we have, even if we are not maintainer of the area, could be beneficial.

So, at least in my case, I'd like to be able to get random issues that are not limited to specific labels and that without stepping on the toes of the actual maintainers (thus why @yrodiere suggested a new category).

**Comment by yrodiere** [comment]
Looks interesting.

That would be limited to stale issues, I assume? No concepts of reproducers here?

Also, could you provide some idea of the delay/timeout? Same as the current "stale" category, i.e. 30 days until first notification, then 30 days between notifications?

Also, about the "random" part, is it enough to just notify progressively from the newest non-notified stale issue to the oldest? Or do you really need me to randomly skip some issues?

And do you need me to skip notifying the stewards when maintainers have been notified "recently" (to be defined)?

Finally... if we end up implementing [notifications for new issues](https://github.com/quarkusio/quarkus-github-lottery/issues/32), would that make sense for stewards too?

**Comment by gsmet** [comment]
I would keep it simple for now and just implement the same rule for stale issues. Just with no filtering.

I think the random part could be interesting though. My idea would have been to just randomly pick the issues. But if it's not feasible, we can live with the current behavior.

**Comment by yrodiere** [comment]
Alright, let's keep it simple for now.

> My idea would have been to just randomly pick the issues. But if it's not feasible, we can live with the current behavior.

I opened #38 with this suggestion along with an explanation of why it's tough.
